### ISSUE TITLE
Will there be devset data for Hñähñu and Shipibo-Konibo?

### ISSUE THREAD

**Issue by alexrudnick** [AmericasNLP/americasnlp2021#12]
Hey there!

For the other language pairs, there are provided dev sets, but for the hñähñu-spanish and shipibo_konibo-spanish language pairs, there are no given dev sets. Is that intended, or should we expect those to be provided later?

Thanks a bunch!

**Comment by pywirrarika** [comment]
Hi! 

up to now we have published dev sets for 6 languages. there are still other languages missing. As we stated in our important dates for the shared task: 
"Release of second batch of development sets and test input: March 01, 2021"
http://turing.iimas.unam.mx/americasnlp/st.html

I hope this helps.

**Comment by pywirrarika** [comment]
All dev sets are online now. :)
