### ISSUE TITLE
Bribri orthography conversion script bug

### ISSUE THREAD

**Issue by svirpioj** [AmericasNLP/americasnlp2021#13]
I suppose mapping commas to dots is a typo here?
```
  punctuation = {
      " .":".", " ,":".", " !":"!", " ?":"?"
  }
```
(https://github.com/AmericasNLP/americasnlp2021/blob/main/data/bribri-spanish/bribri-orthography-conversion.ipynb)

**Comment by pywirrarika** [comment]
Hi! Thank you for finding this issue. I contacted the author of the script and hopefully in the next hours he can answer directly.

**Comment by rolandocoto** [comment]
Hi! Thanks for pointing it out. That is indeed a bug; I have now corrected it.
Thank you for working with the Bribri data!
