### ISSUE TITLE
Extraneous file?

### ISSUE THREAD

**Issue by ftyers** [AmericasNLP/americasnlp2021#3]
There appears to be some Mac special files in the repo: `../data/quechua-spanish/.DS_Store`

**Comment by pywirrarika** [comment]
Thank you for noticing. It seems that it is a MacOS X file that got added to the repo by accident.  I removed the file, and it is not longer there.

**Comment by pywirrarika** [comment]
Thank you for noticing. It seems that it is a MacOS X file that got added to the repo by accident.  I removed the file, and it is not longer there.
