### ISSUE TITLE
ISO language codes seem wrong

### ISSUE THREAD

**Issue by jonorthwash** [AmericasNLP/americasnlp2021#7]
Would it be possible to change the language codes to the ISO-standard codes?  It might help people find resources and avoid people confusing different languages.  These are the ones I have in mind:
`wix`→`hch`
`tnh`→`thh`
`shi`→`shp`

If you don't have time, perhaps the issue could be left as a reference for others?

**Comment by pywirrarika** [comment]
Thank you the ticket. The issue is now fixed.
